### ISSUE TITLE
Reviewer's name and profile URL

### ISSUE THREAD

**Issue by Iysbaera** [petrpatek/tripadvisor-scraper#15]
Hello, is it possible to scrape reviewer's login and profile url as well as text, title, rating etc?

**Comment by petrpatek** [comment]
You would like to get the reviewer's username and profile URL, right?

**Comment by Iysbaera** [comment]
Yes, I like to get reviewer's username and profile URL.
I tried to modify your code, but unfortunately I don't have valid tripadvisor API_KEY for Apify.

**Comment by petrpatek** [comment]
A simple Pr would be nice. Here is the key - 3c7beec8-846d-4377-be03-71cae6145fdc

**Comment by Iysbaera** [comment]
Thank you! It works great.
